#%%
CATEGORIES = [
    {"label": "Normal Type",   "condition": "type_normal = 1"},
    {"label": "Fire Type",     "condition": "type_fire = 1"},
    {"label": "Water Type",    "condition": "type_water = 1"},
    {"label": "Electric Type", "condition": "type_electric = 1"},
    {"label": "Grass Type",    "condition": "type_grass = 1"},
    {"label": "Ice Type",      "condition": "type_ice = 1"},
    {"label": "Fighting Type", "condition": "type_fighting = 1"},
    {"label": "Poison Type",   "condition": "type_poison = 1"},
    {"label": "Ground Type",   "condition": "type_ground = 1"},
    {"label": "Flying Type",   "condition": "type_flying = 1"},
    {"label": "Psychic Type",  "condition": "type_psychic = 1"},
    {"label": "Bug Type",      "condition": "type_bug = 1"},
    {"label": "Rock Type",     "condition": "type_rock = 1"},
    {"label": "Ghost Type",    "condition": "type_ghost = 1"},
    {"label": "Dragon Type",   "condition": "type_dragon = 1"},
    {"label": "Dual Type", "condition": "(type_normal + type_fire + type_water + type_electric + type_grass + type_ice + type_fighting + type_poison + type_ground + type_flying + type_psychic + type_bug + type_rock + type_ghost + type_dragon) > 1"},
    {"label": "Single Type", "condition": "(type_normal + type_fire + type_water + type_electric + type_grass + type_ice + type_fighting + type_poison + type_ground + type_flying + type_psychic + type_bug + type_rock + type_ghost + type_dragon) = 1"},
    {"label": "No Evolution", "condition": "evo_stage = 0"},
    {"label": "First Stage", "condition": "evo_stage = 1 or evo_stage = 0"},
    {"label": "Second Stage", "condition": "evo_stage = 2"},
    {"label": "Third/Final Stage", "condition": "evo_stage = 3"},
    {"label": "No Legs", "condition": "legs = 0"},
    {"label": "Two Legs", "condition": "legs = 2"},
    {"label": "Four Legs", "condition": "legs = 4"},
    {"label": "Six Legs", "condition": "legs = 6"},
    {"label": "Under 500 pounds", "condition": "weight_lbs < 500"},
    {"label": "Over 500 pounds", "condition": "weight_lbs > 500"},
]